.constant	M_SCREEN_CONTROL_BUS_ADDRESS	0x411
.constant	M_SCREEN_CHAR_BUS_ADDRESS	0x412
.constant	M_SCREEN_X_BUS_ADDRESS	0x413
.constant	M_SCREEN_Y_BUS_ADDRESS	0x414
.constant	M_SCREEN_COLOR_BUS_ADDRESS	0x415

.constant	M_KEYPAD_CONTROL_BUS_ADDRESS	0x430
.constant	M_KEYPAD_DATA_BUS_ADDRESS	0x431

.address 0x2000

!main
	MOVI r41, 48
!nothing
	STOR r41, [M_SCREEN_CONTROL_BUS_ADDRESS]
	BRA [!nothing]
